#/*******************************************************************************
# * Copyright (c) 2022 Bosch.IO GmbH and others.
# * 
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * and Eclipse Distribution License v1.0 which accompany this distribution.
# * 
# * The Eclipse Public License is available at
# *    http://www.eclipse.org/legal/epl-v20.html
# * and the Eclipse Distribution License is available at
# *    http://www.eclipse.org/org/documents/edl-v10.html.
# * 
# * Contributors:
# *    Achim Kraus (Bosch.IO GmbH) - initial definition
# *                                  create the service without udp loadbalancer
# ******************************************************************************/

apiVersion: v1
kind: Service
metadata:
  name: cf-extserver
spec:
  selector:
    app: cf-extserver
  type: NodePort
  externalTrafficPolicy: Local
  ports: 
  - name: coap2
    port: 5783
    targetPort: cf-coap2
    nodePort: 30783
    protocol: UDP
  - name: coaps2
    port: 5784
    targetPort: cf-coaps2
    nodePort: 30784
    protocol: UDP
