/*******************************************************************************
 * Copyright (c) 2014, 2015 Institute for Pervasive Computing, ETH Zurich and others.
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 * 
 * The Eclipse Public License is available at
 *    http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 *    http://www.eclipse.org/org/documents/edl-v10.html.
 * 
 * Contributors:
 *    Matthias Kovatsch - creator and main architect
 *    Stefan Jucker - DTLS implementation
 *    Kai Hudalla (Bosch Software Innovations GmbH) - add equals() & hashCode()
 ******************************************************************************/
package org.eclipse.californium.scandium.dtls;

import java.security.SecureRandom;
import java.util.Arrays;

/**
 * A session identifier is a value generated by a server that identifies a
 * particular session.
 */
public class SessionId {
	
	// Members ////////////////////////////////////////////////////////
	
	private byte[] sessionId; // opaque SessionID<0..32>;
	
	// Constructors ///////////////////////////////////////////////////

	public SessionId() {
		sessionId = new Random(new SecureRandom()).getRandomBytes();
	}
	
	/**
	 * Creates a session identifier based on given bytes.
	 * 
	 * @param sessionId the bytes constituting the identifier
	 * @throws NullPointerException if the byte array is <code>null</code>
	 */
	public SessionId(byte[] sessionId) {
		if (sessionId == null) {
			throw new NullPointerException("Session ID must not be null");
		}
		this.sessionId = sessionId;
	}
	
	// Methods ////////////////////////////////////////////////////////
	
	public int length() {
		return sessionId.length;
	}
	
	public byte[] getSessionId() {
		return sessionId;
	}

	/**
	 * Computes a hash code based on the <em>sessionId</em> field.
	 * 
	 * @return the hash code
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + Arrays.hashCode(sessionId);
		return result;
	}

	/**
	 * Checks if this session identifier is equal to another object.
	 * 
	 * Session identifiers are considered equal if all bytes of the
	 * <em>sessionId</em> are equal.
	 * 
	 * @param obj the object to compare to
	 * @return <code>true</code> if the other object is the same as
	 * this one
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SessionId other = (SessionId) obj;
		if (!Arrays.equals(sessionId, other.sessionId))
			return false;
		return true;
	}
	
}
