/*******************************************************************************
 * Copyright (c) 2014 Institute for Pervasive Computing, ETH Zurich and others.
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 * 
 * The Eclipse Public License is available at
 *    http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 *    http://www.eclipse.org/org/documents/edl-v10.html.
 * 
 * Contributors:
 *    Matthias Kovatsch - creator and main architect
 *    Stefan Jucker - DTLS implementation
 ******************************************************************************/
package org.eclipse.californium.scandium.dtls;

import java.security.SecureRandom;

/**
 * A session identifier is a value generated by a server that identifies a
 * particular session.
 */
public class SessionId {
	
	// Members ////////////////////////////////////////////////////////
	
	private byte[] sessionId; // opaque SessionID<0..32>;
	
	// Constructors ///////////////////////////////////////////////////

	public SessionId() {
		sessionId = new Random(new SecureRandom()).getRandomBytes();
	}
	
	public SessionId(byte[] sessionId) {
		this.sessionId = sessionId;
	}
	
	// Methods ////////////////////////////////////////////////////////
	
	public int length() {
		return sessionId.length;
	}
	
	public byte[] getSessionId() {
		return sessionId;
	}
}
