/*******************************************************************************
 * Copyright (c) 2018 RISE SICS and others.
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 * 
 * The Eclipse Public License is available at
 *    http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 *    http://www.eclipse.org/org/documents/edl-v10.html.
 * 
 * Contributors:
 *    Joakim Brorsson
 *    Tobias Andersson (RISE SICS)
 *    Rikard Höglund (RISE SICS)
 *    
 ******************************************************************************/
package org.eclipse.californium.oscore;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.eclipse.californium.core.coap.EmptyMessage;
import org.eclipse.californium.core.coap.Message;
import org.eclipse.californium.core.coap.MessageObserverAdapter;
import org.eclipse.californium.core.coap.OptionNumberRegistry;
import org.eclipse.californium.core.coap.OptionSet;
import org.eclipse.californium.core.coap.Request;
import org.eclipse.californium.core.coap.Response;
import org.eclipse.californium.core.coap.Token;
import org.eclipse.californium.core.network.Exchange;
import org.eclipse.californium.core.network.stack.AbstractLayer;

/**
 * 
 * Applies OSCORE mechanics at stack layer.
 *
 */
public class ObjectSecurityLayer extends AbstractLayer {

	/**
	 * The logger
	 */
	private static final Logger LOGGER = LoggerFactory.getLogger(ObjectSecurityLayer.class.getName());

	private static final byte[] EMPTY = new byte[0];

	/**
	 * Generate a new partial IV for outgoing Response messages.
	 * If this variable is false the same nonce from the original request will be used.
	 * Otherwise a new partial IV will be generated by the sender and included in the Response.
	 * This affects the calculation of the nonce.
	 * 
	 * See https://tools.ietf.org/html/draft-ietf-core-object-security-16#section-5.2
	 *
	 * This variable will control the general behaviour of the sender of Response messages
	 */
	private static boolean responseWithPartialIV = false; 

	/**
	 * Encrypt an outgoing request using the OSCore context.
	 * 
	 * @param message the message
	 * @param ctx the OSCore context
	 * 
	 * @return the encrypted message
	 * 
	 * @throws OSException error while encrypting request
	 */
	public static Request prepareSend(Request message, OSCoreCtx ctx) throws OSException {
		return RequestEncryptor.encrypt(message, ctx);
	}

	/**
	 * Encrypt an outgoing response using the OSCore context.
	 * 
	 * @param message the message
	 * @param ctx the OSCore context
	 * 
	 * @return the encrypted message
	 * 
	 * @throws OSException error while encrypting response
	 */
	public static Response prepareSend(Response message, OSCoreCtx ctx, final boolean newPartialIV) throws OSException {
		return ResponseEncryptor.encrypt(message, ctx, newPartialIV);
	}

	/**
	 * Decrypt an incoming request using the right OSCore context
	 * 
	 * @param request the incoming request
	 * 
	 * @return the decrypted and verified request
	 * 
	 * @throws OSException error while decrypting request
	 */
	public static Request prepareReceive(Request request) throws CoapOSException {
		return RequestDecryptor.decrypt(request);
	}

	/**
	 * Decrypt an incoming response using the right OSCore context
	 * 
	 * @param response the incoming request
	 * @return the decrypted and verified response
	 * 
	 * @throws OSException error while decrypting response
	 */
	public static Response prepareReceive(Response response) throws OSException {
		return ResponseDecryptor.decrypt(response);
	}

	@Override
	public void sendRequest(Exchange exchange, Request request) {
		Request req = request;
		if (shouldProtectRequest(request)) {
			try {
				String uri = request.getURI();
				final OSCoreCtxDB db = HashMapCtxDB.getInstance();

				if (uri == null) {
					LOGGER.error(ErrorDescriptions.URI_NULL);
					throw new OSException(ErrorDescriptions.URI_NULL);
				}
				if (db == null) {
					LOGGER.error(ErrorDescriptions.DB_NULL);
					throw new OSException(ErrorDescriptions.DB_NULL);
				}

				final OSCoreCtx ctx = db.getContext(uri);
				if (ctx == null) {
					LOGGER.error(ErrorDescriptions.CTX_NULL);
					throw new OSException(ErrorDescriptions.CTX_NULL);
				}

				exchange.setCryptographicContextID(ctx.getRecipientId());
				final int seqByToken = ctx.getSenderSeq();

				final Request preparedRequest = prepareSend(request, ctx);
				preparedRequest.addMessageObserver(new MessageObserverAdapter() {

					@Override
					public void onReadyToSend() {
						Token token = preparedRequest.getToken();
						db.addContext(token, ctx);
						db.addSeqByToken(token, seqByToken);
					}
				});

				req = preparedRequest;

			} catch (OSException e) {
				LOGGER.error("Error sending request: " + e.getMessage());
				return;
			} catch (IllegalArgumentException e) {
				LOGGER.error("Unable to send request because of illegal argument: " + e.getMessage());
				return;
			}
		}
		LOGGER.info("Request: " + exchange.getRequest().toString());
		super.sendRequest(exchange, req);
	}

	@Override
	public void sendResponse(Exchange exchange, Response response) {
		/* Check if the request contained the Observe option.
		 * If so always add a partial IV to the response.
		 * A partial IV will also be added if the responseWithPartialIV flag is set. */
		boolean addPartialIV = responseWithPartialIV || exchange.getRequest().getOptions().hasObserve();
		
		if (shouldProtectResponse(exchange)) {
			try {
				HashMapCtxDB db = HashMapCtxDB.getInstance();
				OSCoreCtx ctx = db.getContext(exchange.getCryptographicContextID());
				response = prepareSend(response, ctx, addPartialIV);
				exchange.setResponse(response);
			} catch (OSException e) {
				LOGGER.error("Error sending response: " + e.getMessage());
				return;
			}
		}
		super.sendResponse(exchange, response);
	}

	@Override
	public void sendEmptyMessage(Exchange exchange, EmptyMessage message) {
		super.sendEmptyMessage(exchange, message);
	}

	@Override
	public void receiveRequest(Exchange exchange, Request request) {
		if (isProtected(request)) {
			byte[] rid = null;
			try {
				request = prepareReceive(request);
				rid = request.getOptions().getOscore();
				request.getOptions().setOscore(EMPTY);
				exchange.setRequest(request);
			} catch (CoapOSException e) {
				LOGGER.error("Error while receiving OSCore request: " + e.getMessage());
				Response error;
				error = CoapOSExceptionHandler.manageError(e, request);
				if (error != null) {
					super.sendResponse(exchange, error);
				}
				return;
			}
			exchange.setCryptographicContextID(rid);
		}
		super.receiveRequest(exchange, request);
	}

	//Always accepts unprotected responses, which is needed for reception of error messages
	@Override
	public void receiveResponse(Exchange exchange, Response response) {
		Request request = exchange.getCurrentRequest();
		if (request == null) {
			LOGGER.error("No request tied to this response");
			return;
		}
		try {
			//Printing of status information.
			//Warns when expecting OSCORE response but unprotected response is received
			if (!isProtected(response) && responseShouldBeProtected(exchange, response)) {
				LOGGER.warn("Incoming response is NOT OSCORE protected!");
			} else if (isProtected(response)) {
				LOGGER.info("Incoming response is OSCORE protected");
			}

			//If response is protected with OSCORE parse it first with prepareReceive
			if (isProtected(response)) {
				response = prepareReceive(response);
			}
		} catch (OSException e) {
			LOGGER.error("Error while receiving OSCore response: " + e.getMessage());
			EmptyMessage error = CoapOSExceptionHandler.manageError(e, response);
			if (error != null) {
				sendEmptyMessage(exchange, error);
			}
			return;
		}
		
		//Remove token if this is a response to a Observe cancellation request
		if(exchange.getRequest().isObserveCancel()) {
			OSCoreCtxDB db = HashMapCtxDB.getInstance();
			db.removeToken(response.getToken());
		}
		
		super.receiveResponse(exchange, response);
	}

	@Override
	public void receiveEmptyMessage(Exchange exchange, EmptyMessage message) {
		super.receiveEmptyMessage(exchange, message);
	}

	private static boolean shouldProtectResponse(Exchange exchange) {
		return exchange.getCryptographicContextID() != null;
	}

	//Method that checks if a response is expected to be protected with OSCORE
	private static boolean responseShouldBeProtected(Exchange exchange, Response response) throws OSException {
		Request request = exchange.getCurrentRequest();
		OptionSet options = request.getOptions();
		if (exchange.getCryptographicContextID() == null) {
			if (response.getOptions().hasObserve() && request.getOptions().hasObserve()) {

				// Since the exchange object has been re-created the
				// cryptographic id doesn't exist
				if (options.hasOscore()) {
					String uri = request.getURI();
					OSCoreCtxDB db = HashMapCtxDB.getInstance();
					OSCoreCtx ctx = null;
					try {
						ctx = db.getContext(uri);
					} catch (OSException e) {
						LOGGER.error("Error when re-creating exchange at OSCORE level");
						throw new OSException("Error when re-creating exchange at OSCORE level");
					}
					exchange.setCryptographicContextID(ctx.getRecipientId());
				}
			}
		}
		return exchange.getCryptographicContextID() != null;
	}

	private static boolean shouldProtectRequest(Request request) {
		OptionSet options = request.getOptions();
		return options.hasOption(OptionNumberRegistry.OSCORE);

	}

	private static boolean isProtected(Message message) {
		return message.getOptions().getOscore() != null;
	}
}
