# Site settings
baseurl = "https://www.eclipse.org/californium/"
languageCode = "en-us"
title = "Eclipse Californium&trade;"
theme = "syna"
enableGitInfo = false
version = "0.17.4"

# Google Analytics tracking
googleAnalytics = ""

[markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[params]
  name = "Eclipse Californium project"
  description = "A Java framework for implementing CoAP clients and servers"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
#    favicon = "favicon.ico"
#    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "images/logos/Cf_32.png"
#    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
#[[menu.main]]
#  url = "/"
#  name = "Home"
#  weight = 10

[[menu.main]]
  url = "#getting-started"
  name = "Getting Started"
  weight = 20

[[menu.main]]
  url = "#community"
  name = "Community"
  weight = 30

[[menu.footer]]
  url = "https://www.eclipse.org/legal/privacy.php"
  name = "Privacy Policy"
  weight = 10

[[menu.footer]]
  url = "https://www.eclipse.org/legal/termsofuse.php"
  name = "Terms of Use"
  weight = 20

[[menu.footer]]
  url = "https://www.eclipse.org/legal/copyright.php"
  name = "Copyright Agent"
  weight = 30

[[menu.footer]]
  url = "https://www.eclipse.org/legal/"
  name = "Legal"
  weight = 40

[[menu.footer]]
  url = "https://www.eclipse.org/legal/epl-2.0/"
  name = "License"
  weight = 50

[[menu.footer]]
  url = "https://eclipse.org/security/"
  name = "Report a Vulnerability"
  weight = 60

#[[menu.copyright_footer]]
#  url = "/about"
#  name = "About Us"
#  weight = 10

#[[menu.copyright_footer]]
#  url = "#"
#  name = "Another Link"
#  weight = 30

#[[menu.footer_social]]
#  weight = 20
#  name = "github"
#  pre = "fab fa-github"
# url = "https://github.com/eclipse/californium"

#[[menu.footer_social]]
#  weight = 30
#  name = "linkedin"
#  pre = "fab fa-linkedin-in"
#  url = "#"
